version: '3'

services:
  database:
    image: postgres
    env_file:
      - env_var/database.env
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - emenu-network

  api:
    build: .
    env_file:
      - env_var/api.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./emenu:/code
    ports:
      - "8000:8000"
    depends_on:
      - database
      - migration
    networks:
      - emenu-network

  migration:
    build: .
    env_file:
      - env_var/api.env
    command: >
      bash -c "wait-for-it database:5432 --
      python manage.py migrate --noinput"
    volumes:
      - ./emenu:/code
    depends_on:
      - database
    networks:
      - emenu-network

networks:
  emenu-network:
