# Generated by Django 3.1.1 on 2020-09-29 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_menu_and_dish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dishes",
                to="api.menu",
            ),
        ),
    ]
